### ISSUE TITLE
native_build not building

### ISSUE THREAD

**Issue by BestSinSoo** [covers1624/curl4j#15]
Hello,

native_build not building.
build/libs/curl4j-3.0.8.jar file is generated. However, there are no native files inside this file.
What should I do?

**Comment by covers1624** [comment]
Natives must be built manually via the Makefile inside `native_build` prior to running Gradle.

The CI is the best example of this, it requires some env vars to know which OS/Arch you are building for to enable/disable certain options.

If you just want the jni libraries built and plan to BYO libcurl, you can use the `build-libcurl4j` make target.
